# Obesity Trend Analysis in India 
## NFHS-5 (2019-20)
### Step 1: Cleaning the dataset

### Step 1: Importing Important Libraries

In [ ]:
import pandas as pd
import numpy as np
print("Libraries Imported Successfully")

Libraries imported successfully

### Step 2: Loading the Dataset 
**Source:** NFHS-5 (2019-20), Ministry of Health and Family Welfare, Government of India

In [ ]:
df = pd.read_excel('../data/raw/Obesity_Analysis.xlsx', na_values=['NA', 'N/A', '', ' '])
print("Data Loaded Successfully")

Data loaded successfully

### Step 3: Checking the Shape of the Dataset

In [3]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 36
Columns: 17

### Step 4: Preview the Dataset

In [4]:
df.head()

,state,regions,overweight_obese_w,overweight_obese_m,education_w,education_m,income(in Rs.),tobacco_w,tobacco_m,alcohol_w,alcohol_m,internet_w,internet_m,blood_sugar_w,blood_sugar_m,bp_w,bp_m
0,Andaman and Nicobar Islands,South,38.1,45.3,52.5,52.3,197278.0,31.3,58.7,5.0,39.1,34.8,46.5,17.5,17.9,25.3,30.2
1,Andhra Pradesh,South,36.3,31.1,39.6,47.9,163746.0,3.8,22.6,0.5,23.3,21.0,48.8,19.5,21.8,25.3,29.0
2,Arunachal Pradesh,Northeast,23.9,27.6,39.4,48.2,190212.0,18.8,50.3,24.2,52.7,52.9,71.6,8.4,11.9,24.9,33.1
3,Assam,Northeast,15.2,16.2,29.6,35.5,90482.0,22.1,51.8,7.3,25.1,28.2,42.3,12.8,16.0,19.1,20.3
4,Bihar,East,15.9,14.7,28.8,42.8,43605.0,5.0,48.8,0.4,15.5,20.6,43.6,12.7,16.2,15.9,18.4

### Step 5: Checking Data Types

In [5]:
df.dtypes

state                  object
regions                object
overweight_obese_w    float64
overweight_obese_m    float64
education_w           float64
education_m           float64
income(in Rs.)        float64
tobacco_w             float64
tobacco_m             float64
alcohol_w             float64
alcohol_m             float64
internet_w            float64
internet_m            float64
blood_sugar_w         float64
blood_sugar_m         float64
bp_w                  float64
bp_m                  float64
dtype: object

### Step 6: Checking Missing Values

In [6]:
df.isnull().sum()

state                 0
regions               0
overweight_obese_w    0
overweight_obese_m    0
education_w           0
education_m           0
income(in Rs.)        3
tobacco_w             0
tobacco_m             0
alcohol_w             0
alcohol_m             0
internet_w            0
internet_m            0
blood_sugar_w         0
blood_sugar_m         0
bp_w                  0
bp_m                  0
dtype: int64

### Step 7: Identifying Missing Income States

In [7]:
df[df['income(in Rs.)'].isnull()][['state','regions']]

                                       state regions
7   Dadra and Nagar Haveli and Daman and Diu    West
16                                    Ladakh   North
17                               Lakshadweep   South

### Step 8: Fixing Income Data Type

In [8]:
df['income(in Rs.)'] = df['income(in Rs.)'].astype('Int64')

print("Done!")
df.head()

Done!

,state,regions,overweight_obese_w,overweight_obese_m,education_w,education_m,income(in Rs.),tobacco_w,tobacco_m,alcohol_w,alcohol_m,internet_w,internet_m,blood_sugar_w,blood_sugar_m,bp_w,bp_m
0,Andaman and Nicobar Islands,South,38.1,45.3,52.5,52.3,197278,31.3,58.7,5.0,39.1,34.8,46.5,17.5,17.9,25.3,30.2
1,Andhra Pradesh,South,36.3,31.1,39.6,47.9,163746,3.8,22.6,0.5,23.3,21.0,48.8,19.5,21.8,25.3,29.0
2,Arunachal Pradesh,Northeast,23.9,27.6,39.4,48.2,190212,18.8,50.3,24.2,52.7,52.9,71.6,8.4,11.9,24.9,33.1
3,Assam,Northeast,15.2,16.2,29.6,35.5,90482,22.1,51.8,7.3,25.1,28.2,42.3,12.8,16.0,19.1,20.3
4,Bihar,East,15.9,14.7,28.8,42.8,43605,5.0,48.8,0.4,15.5,20.6,43.6,12.7,16.2,15.9,18.4

### Step 9: Strip any extra spaces from column names

In [9]:
df.columns = df.columns.str.strip()
print("Successfull")

Successfull

### Step 10: Renaming Columns

In [10]:
df.rename(columns={
    'income(in Rs.)' : 'income',
    'regions'        : 'zone'
}, inplace=True)

print(df.columns.tolist())

['state', 'zone', 'overweight_obese_w', 'overweight_obese_m', 'education_w', 'education_m', 'income', 'tobacco_w', 'tobacco_m', 'alcohol_w', 'alcohol_m', 'internet_w', 'internet_m', 'blood_sugar_w', 'blood_sugar_m', 'bp_w', 'bp_m']

### Step 11: Save cleaned dataset

In [11]:
df.to_csv('../data/processed/obesity_cleaned.csv',index=False)
print("Saved Successfully!")

Saved Successfully!